//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AarhusHostelDBEntities : DbContext
    {
        public AarhusHostelDBEntities()
            : base("name=AarhusHostelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrugerTable> BrugerTable { get; set; }
        public virtual DbSet<FotoTable> FotoTable { get; set; }
        public virtual DbSet<MulighederTable> MulighederTable { get; set; }
        public virtual DbSet<VaerlseTable> VaerlseTable { get; set; }
    }
}
