//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MulighederTable
    {
        public int MulighedID { get; set; }
        public string MulighedOverskrift { get; set; }
        public string MulighedText { get; set; }
        public string MulighedFoto { get; set; }
    }
}
