//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaerlseTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VaerlseTable()
        {
            this.FotoTable = new HashSet<FotoTable>();
        }
    
        public int ItemID { get; set; }
        public string ItemNavn { get; set; }
        public string ItemBeskerivlse { get; set; }
        public string fastText { get; set; }
        public Nullable<int> PrisMedToilet { get; set; }
        public Nullable<int> PrisMedFaellsToilet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotoTable> FotoTable { get; set; }
    }
}
